#server.port = 8181 #properties


#server:
#  port: 8181
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/demodb
    username: root
    password: mariadb
logging:
  level:
    root: info
    com:
      example:
        apibasic:
          req: trace

springdoc:
  swagger-ui:
    path: /myapi.html